brand 페이지 작업, 네비게이션 메뉴 css 수정, header css 수정, fullpage.js 적용
biocourt/websites pull request #80
Opened 2022-05-20 05:39 UTC by cmleeee

fullPage.js 하다 보니 여러군데 작게 작게 header랑 navigation 건드려서 같이 올립니다

2022-05-20 05:40 UTC, cmleeee commented
![햄버거메뉴](https://user-images.githubusercontent.com/96406855/169458283-98c20086-fff1-4385-8205-a328ae08bf94.gif)
화면 줄일때 이렇게 되는거 거슬리는데 방법이 없을까요,,,

2022-05-20 05:42 UTC, cmleeee commented
그리고 네비게이션때문에 화면 사이즈를 줄이면 다른 섹션 페이지들이 깔려 있어서 hover가 안먹어요!
z-index 나  opacity를 해도 해결이 안되네요..

2022-05-20 05:42 UTC, XiNiHa commented
음 한번 만져보고 알려드릴게요

2022-05-20 06:15 UTC, XiNiHa commented
> 화면 줄일때 이렇게 되는거 거슬리는데 방법이 없을까요,,,

이거는 뭐 두 개 만드는 거 외에는 방법이 없어 보이는데 그냥 둬도 괜찮을 것 같긴 해요

>그리고 네비게이션때문에 화면 사이즈를 줄이면 다른 섹션 페이지들이 깔려 있어서 hover가 안먹어요!
z-index 나 opacity를 해도 해결이 안되네요..

이건 수정해서 올려둘게요

2022-05-20 06:19 UTC, XiNiHa commented
근데 `background-image` 쓰시면 Astro 빌드하면 안 먹으니까 `<img>`로 써주시면 좋을 것 같아요
추후에 이미지 최적화도 들어가려면 `background-image`는 못 쓰기도 하고

2022-05-23 04:07 UTC, XiNiHa requested changes

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +        <div
1. `<button>`으로 바꿔주시고
2. 타 섹션에서도 사용될 예정이면 컴포넌트로 빼 주세요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +          w-flex="~"
`flex` 아니어도 괜찮을 것 같고요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +          w-cursor="pointer"
`<button>`으로 바꾸시면 이것도 빼셔도 될 거고요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +          w-m="r-[33px]"
마진을 넣는 대신 상위 컨테이너에서 `gap`을 쓰는 게 나을 것 같아요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +    class="section0"
`w-object="cover center-[80%]"` (뒤에 건 안 될수도 있어요) 하고 아래 `<style>` 지워주시는 게 나을 것 같아요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/layout/header/Navgation.astro
> +  <div
얘도 `<button>`이 돼야 맞아 보이고, 그러면 아래 `cursor="pointer"`도 지우시면 되고요

2022-05-23 04:07 UTC, XiNiHa commented on apps/welcoach-hero/src/styles/nav.css
> +}
이거 쓰는 곳 없는 것 같은데 전부 지워주세요

2022-05-23 04:11 UTC, cmleeee commented on apps/welcoach-hero/src/components/units/Brand.astro
> +  <img
밑에 색 말씀이신가요.,.?

2022-05-23 04:13 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +  <img
네넹 저 하얀 거요.....ㅋㅋㅋㅋㅋㅋ 로고 가리려고 이레씨가 넣으신 건가

2022-05-30 07:29 UTC, cmleeee commented
https://xd.adobe.com/view/2aae0932-1aaf-4752-aead-59d5b9041a16-7ffd/grid
여기 히어로 페이지 디자인입니다!

2022-05-30 08:13 UTC, XiNiHa requested changes
내비게이션 들어갔다 나왔다 할 때 배경에 transition이 없어서 좀 거슬리는데 넣어주시면 좋을 것 같아요

2022-05-30 08:13 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +    <div w-flex="~ col">
<img width="1262" alt="스크린샷 2022-05-30 오후 5 06 37" src="https://user-images.githubusercontent.com/8155259/170947671-1519bdec-123f-4b35-b235-61d74c28a967.png">
Breakpoint 경계에 걸렸을 때 좀 보기 흉한 것 같아서 상위 요소에 가로 padding을 넣든 하는 게 좋지 않을까 싶어요

2022-05-30 08:13 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Brand.astro
> +          <p w-display="<md:hidden">(미국 전역 2,000여개 검사소 보유)</p>
```suggestion
          <p w-flex="~ <md:col" w-items="md:center" w-m="b-4">
            세계 1위 혈액분석기관
            <span w-flex="~" w-items="center">
              <img
                src={Labcorp}
                width="133"
                height="36"
                w-m="md:x-2 <md:y-2"
                w-w="max-133px <md:106px"
                w-h="max-36px <md:29px"
              />(랩콥)에서
            </span>
            건강을 확인할 수 있습니다.
          </p>
          <p w-display="<md:hidden">(미국 전역 2,000여개 검사소 보유)</p>
```

2022-05-31 08:20 UTC, XiNiHa reviewed
위에서 padding 추가 요청드렸던 것 반영이 안 된 것 같아요

2022-06-03 07:29 UTC, XiNiHa requested changes
... 정작 padding 추가는 안 됐고 코멘트는 해결 안 된 게 Resolve 처리 되어 있고 이용방법 쪽 작업하시던 게 섞여들어온 것 같은...
수정 후 재요청 부탁드려요

2022-06-07 06:16 UTC, XiNiHa approved these changes

2022-06-07 06:16 UTC, merged