Menual 페이지 추가
biocourt/websites pull request #81
Opened 2022-05-31 08:03 UTC by cmleeee

아직 작업이 덜됐는데 시간이 없어 보이셔서 ㅋㅋ
중간점검 한번 부탁 드립니다.

2022-05-31 08:04 UTC, cmleeee commented
<img width="2007" alt="image" src="https://user-images.githubusercontent.com/96406855/171123736-b1566adc-2e4f-40e0-b09c-5342018f67a0.png">
그리고 여기 있는 구매하기 버튼이 상위 페이지 Brand 페이지에서는 안보여야하는데 혹시 어떻게 처리 해야할까요

2022-05-31 08:33 UTC, XiNiHa requested changes
> 그리고 여기 있는 구매하기 버튼이 상위 페이지 Brand 페이지에서는 안보여야하는데 혹시 어떻게 처리 해야할까요 

`position: sticky`를 활용해보시면 될 것 같네요.... 근데 이거 저번에도 정확히 똑같은 걸 질문하셨던 것 같은데 기분 탓이려나요 (?)

2022-05-31 08:33 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Menual.astro
> +      <ul class="detail-wrap" w-flex="~ col" w-justify="between" w-h="full">
여기도 마찬가지로 `<ul>`이 되어야 할 것 같고요

2022-05-31 08:33 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Menual.astro
> +  const detailWrap = document.querySelector('detail-wrap')
셀렉터에 `.`가 빠진 것....같네요

2022-06-02 05:37 UTC, XiNiHa commented
아 fullpage.js 때문에 잘 작동을 안 할 수도 있겠다는 생각은 들긴 하네요...

2022-06-09 07:36 UTC, cmleeee commented
[PC버전 ](https://xd.adobe.com/view/2aae0932-1aaf-4752-aead-59d5b9041a16-7ffd/screen/a20fbc20-ad47-4fa8-89c1-af3e57e4bd1e/specs/)

[Mobile 버전](https://xd.adobe.com/view/2aae0932-1aaf-4752-aead-59d5b9041a16-7ffd/screen/6821af94-6916-478b-a4fd-1fe17fdd364f/specs/)

2022-06-10 02:31 UTC, XiNiHa requested changes

2022-06-10 02:31 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Menual.astro
> +    transition: 0.3s ease-out;
개인적으론 `0.5s ease` 정도가 보기 편했던 것 같아요

2022-06-10 02:31 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Menual.astro
> +    }
어케....잘....구조화를 시켜볼 수 있지 않을까 싶어요
수치가 규칙적이다 보니

2022-06-14 09:01 UTC, XiNiHa requested changes

2022-06-14 09:01 UTC, XiNiHa commented on apps/welcoach-hero/src/components/units/Menual.astro
> +  })
```suggestion
  tabBar.forEach((el, idx) => {
    el.onclick = () => {
      scrolls.scroll({ left: el.offsetLeft, behavior: 'smooth' })
      slideBar.style.left = `${idx * (mediaQuery.matches ? 50 : 25)}%`
      tabSlider.style.transform = `translateX(${idx * -100}%)`
    }
  })
```
이걸 기대했던.....거였다는

2022-06-14 23:11 UTC, cmleeee commented on apps/welcoach-hero/src/components/units/Menual.astro
> +  })
아 그러네요,,, 수치가 일정해서 그게 되네요 ㅋㅋㅋㅋ 😅

2022-06-15 09:24 UTC, XiNiHa commented
@cmleeee 어찌어찌...Sticky도 구현하고... 모바일에서 탭바 사용성도 개선하고.... 했습니다

2022-06-15 09:24 UTC, XiNiHa approved these changes

2022-06-15 09:27 UTC, merged

2022-06-16 00:06 UTC, cmleeee commented
@XiNiHa  와 근데 제가 이렇게 해볼까 안대겟지 생각한거 다 구현하셧네요ㅕ😧